---
title: AppX
description: Removes AppX packages and prevents them from being reinstalled
actions:
  - !writeStatus: {status: 'Removing AppX packages'}
  
  # The reason of removing those applications is that there is a potential of them sending user data,
  # showing unwanted content (advertisements) and using hardware resources. They can also simply be
  # annoyances that are never used. However, most of these applications can be reinstalled via the
  # Microsoft Store in case the user needs them.

  # https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10

  #####################################################################################################

  # Get current AppX packages to deprovision removed ones later
  - !powerShell:
    command: >-
      (Get-AppxPackage).PackageFamilyName |
      Out-File """$([Environment]::GetFolderPath('Windows'))\AtlasModules\AtlasPackagesOld.txt"""
    runas: currentUserElevated

  # AppX Microsoft Teams
  # Seems legacy - not in 23H2?
  - !taskKill: {name: 'msteams*', ignoreErrors: true}
  - !appx: {name: 'MicrosoftTeams*', type: family}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Communications', value: 'ConfigureChatAutoInstall', data: '0', type: REG_DWORD}

  - !appx: {name: 'Clipchamp.Clipchamp*', type: family}
  - !appx: {name: 'Disney.37853FC22B2CE*', type: family}
  - !appx: {name: 'Microsoft.549981C3F5F10*', type: family} # Cortana
  - !appx: {name: 'Microsoft.XboxApp*', type: family} # Legacy Xbox Console Companion
  - !appx: {name: 'Microsoft.Getstarted*', type: family} # Tips
  - !appx: {name: 'MicrosoftCorporationII.MicrosoftFamily*', type: family}
  - !appx: {name: 'Microsoft.MixedReality.Portal*', type: family}
  - !appx: {name: 'Microsoft.Windows.DevHome*', type: family}
  - !appx: {name: 'Microsoft.BingWeather*', type: family}
  - !appx: {name: 'Microsoft.BingNews*', type: family}
  - !appx: {name: 'Microsoft.OutlookForWindows*', type: family}
  - !appx: {name: 'Microsoft.GetHelp*', type: family}
  - !appx: {name: 'Microsoft.Microsoft3DViewer*', type: family}
  - !appx: {name: 'Microsoft.MicrosoftOfficeHub*', type: family}
  - !appx: {name: 'Microsoft.MicrosoftSolitaireCollection*', type: family}
  - !appx: {name: 'Microsoft.MicrosoftStickyNotes*', type: family}
  - !appx: {name: 'Microsoft.Office.OneNote*', type: family}
  - !appx: {name: 'Microsoft.People*', type: family}
  - !appx: {name: 'Microsoft.PowerAutomateDesktop*', type: family}
  - !appx: {name: 'Microsoft.ScreenSketch*', type: family}
  - !appx: {name: 'Microsoft.SkypeApp*', type: family}
  - !appx: {name: 'Microsoft.Todos*', type: family}
  - !appx: {name: 'Microsoft.WindowsAlarms*', type: family}
  - !appx: {name: 'Microsoft.WindowsCamera*', type: family}
  - !appx: {name: 'Microsoft.WindowsFeedbackHub*', type: family}
  - !appx: {name: 'Microsoft.WindowsMaps*', type: family}
  - !appx: {name: 'Microsoft.YourPhone*', type: family}

  # Prevent provisioned applications from being reinstalled
  # https://learn.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update
  - !powerShell:
    command: >-
      $a = """$([Environment]::GetFolderPath('Windows'))\AtlasModules\AtlasPackagesOld.txt""";
      (diff (gc $a) ((Get-AppxPackage).PackageFamilyName)).InputObject | 
      Foreach-Object { New-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned" -Name $_ -Force }; 
      Remove-Item $a -Force
    runas: currentUserElevated

  # Clear caches of Client.CBS and more
  - !writeStatus: {status: 'Clearing AppX caches'}
  - !appx: {operation: clearCache, name: '*MicrosoftWindows.Client.CBS*'}
  - !appx: {operation: clearCache, name: '*Microsoft.Windows.Search*'}
  - !appx: {operation: clearCache, name: '*Microsoft.Windows.SecHealthUI*'}
